<%!
    # Helper function to generate insertion sort code
    def generate_insertion_sort_code():
        return '''
from typing import List


def insertion_sort(arr: List[int]) -> List[int]:
    for i in range(1, len(arr)):
        key = arr[i]
        j = i - 1
        while j >= 0 and arr[j] > key:
            arr[j + 1] = arr[j]
            j -= 1
        arr[j + 1] = key

'''
%>

# Insertion sort implementation generated by Mako
${generate_insertion_sort_code()}
